global:
  scrape_interval:     15s

  external_labels:
    monitor: 'hop-node-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: http://localhost:9090/api/v1/write
    basic_auth:
      username: admin
      password_file: /prometheus_pass.txt
