version: 2.1

orbs:
  base: dmx-io/base@2.0.88

jobs:
  build_hop_node:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_IMAGE=hopprotocol/hop-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add bash
            apk add curl
            apk add jq
            apk add py-pip=9.0.0-r1
            apk add diffutils
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            cd packages/hop-node
            bash ./ci/package_check.sh
            docker build \
              -f Dockerfile \
              --no-cache \
              --build-arg=GIT_REV=$CIRCLE_SHA1 \
              -t app .
      - deploy:
          name: Push Hop Node Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export BRANCH=$(echo $CIRCLE_BRANCH | sed 's/\//-/g' | sed 's/-bonder//g')
            docker tag app $DOCKER_IMAGE:$CIRCLE_SHA1
            docker tag app $DOCKER_IMAGE:$BRANCH
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $DOCKER_IMAGE:$BRANCH
            test $BRANCH == "production" && docker tag app $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest; true

  build_stats_worker:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_IMAGE=hopprotocol/stats-worker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add bash
            apk add curl
            apk add jq
            apk add py-pip=9.0.0-r1
            apk add diffutils
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            cd packages/stats-worker
            bash ./ci/package_check.sh
            docker build \
              -f Dockerfile \
              --no-cache \
              --build-arg=GIT_REV=$CIRCLE_SHA1 \
              -t app .
      - deploy:
          name: Push Hop Stats Worker Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export BRANCH=$(echo $CIRCLE_BRANCH | sed 's/\//-/g')
            docker tag app $DOCKER_IMAGE:$CIRCLE_SHA1
            docker tag app $DOCKER_IMAGE:$BRANCH
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $DOCKER_IMAGE:$BRANCH
            test $BRANCH == "stats-worker" && docker tag app $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest; true

  build_hop_api:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_IMAGE=hopprotocol/hop-api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add bash
            apk add curl
            apk add jq
            apk add py-pip=9.0.0-r1
            apk add diffutils
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            cd packages/api
            bash ./ci/package_check.sh
            docker build \
              -f Dockerfile \
              --no-cache \
              --build-arg=GIT_REV=$CIRCLE_SHA1 \
              -t app .
      - deploy:
          name: Push Hop Api Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export BRANCH=$(echo $CIRCLE_BRANCH | sed 's/\//-/g')
            docker tag app $DOCKER_IMAGE:$CIRCLE_SHA1
            docker tag app $DOCKER_IMAGE:$BRANCH
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $DOCKER_IMAGE:$BRANCH
            test $BRANCH == "hop-api" && docker tag app $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest; true
workflows:
  main:
    jobs:
      - build_hop_node:
          filters:
            branches:
              only:
                - production-bonder
                - mainnet-bonder
                - staging-bonder
                - develop-bonder
                - goerli-bonder
                - kovan-bonder
                - rinkeby-bonder
              ignore: /.*/
      - build_stats_worker:
          filters:
            branches:
              only:
                - stats-worker
              ignore: /.*/
      - build_hop_api:
          filters:
            branches:
              only:
                - hop-api
              ignore: /.*/