version: '3'

services:
  geth_l2:
    image: ethereumoptimism/go-ethereum:latest
    restart: unless-stopped
    volumes:
      - geth:/root/.ethereum:rw
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545
      - 8546:8546

  batch_submitter:
    restart: unless-stopped
    image: ethereumoptimism/batch-submitter:latest
    env_file:
      - docker-compose.env

volumes:
  geth:
